# Generated by Django 5.0.6 on 2024-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_socio_fecha_inscripcion_alter_socio_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
