# Generated by Django 5.0.6 on 2024-06-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_disciplina_persona_delete_pago_delete_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.PositiveIntegerField(unique=True, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cuit', models.CharField(max_length=100, unique=True, verbose_name='CUIT')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.PositiveIntegerField(unique=True, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddConstraint(
            model_name='profe',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email'),
        ),
    ]
