# Generated by Django 5.0.6 on 2024-06-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_profe_socio_delete_persona_profe_unique_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='disciplina',
            name='profe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.profe'),
        ),
    ]
