# Generated by Django 5.0.6 on 2024-06-05 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_disciplina_options_disciplina_profe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='profe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='club.profe'),
        ),
    ]
