# Generated by Django 5.0.6 on 2024-06-10 04:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_alter_disciplina_profe'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de alta'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.disciplina')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.socio')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='socios',
            field=models.ManyToManyField(through='club.Inscripcion', to='club.socio'),
        ),
    ]
